[theme]
primaryColor = "#7c3aed"             # Фіолетовий для активних елементів (кнопки, активна секція)
backgroundColor = "#FFFFFF"           # Основний фон контенту (білий)
secondaryBackgroundColor = "#60C5FF" # Фон бокової панелі (блакитний)
textColor = "#000000"                 # Колір тексту
font = "sans serif"                   # Шрифт
